AWSTemplateFormatVersion: '2010-09-09'
Description: Volume for Postgres data

Resources:
  PostgresVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs:
            Ref: AWS::Region
      VolumeType: gp2
      Size: 20
      Encrypted: false
      MultiAttachEnabled: false

Outputs:
  PostgresVolumeId:
    Description: Postgres Volume Id
    Value: !Ref PostgresVolume
