pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

variables:
  AWS.Region: 'us-east-1'

steps:
- task: CloudFormationCreateOrUpdateStack@1
  displayName: 'Create Stack: EKS VPC'
  inputs:
    awsCredentials: 'CodeFuller @ AWS'
    stackName: 'eks-vpc'
    templateSource: 'file'
    templateFile: 'eks-vpc.yaml'
    captureStackOutputs: asVariables
    captureAsSecuredVars: false

- task: CloudFormationCreateOrUpdateStack@1
  displayName: 'Create Stack: EKS Cluster Role'
  inputs:
    awsCredentials: 'CodeFuller @ AWS'
    stackName: 'eks-cluster-role'
    templateSource: 'file'
    templateFile: 'eks-cluster-role.yaml'
    captureStackOutputs: asVariables
    captureAsSecuredVars: false

- task: CloudFormationCreateOrUpdateStack@1
  displayName: 'Create Stack: EKS Cluster'
  inputs:
    awsCredentials: 'CodeFuller @ AWS'
    stackName: 'eks-cluster'
    templateFile: 'eks-cluster.yaml'
    templateParametersSource: inline
    templateParameters: |
     - ParameterKey: RoleArn
       ParameterValue: '$(RoleArn)'
     - ParameterKey: SubnetIds
       ParameterValue: '$(SubnetIds)'
