pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

variables:
  AWS.Region: 'us-east-1'

steps:
- task: CloudFormationCreateOrUpdateStack@1
  displayName: 'Create Stack: EKS VPC'
  inputs:
    awsCredentials: 'CodeFuller @ AWS'
    stackName: 'eks-vpc'
    templateSource: 'file'
    templateFile: 'eks-vpc.yaml'

- task: CloudFormationCreateOrUpdateStack@1
  displayName: 'Create Stack: EKS Cluster Role'
  inputs:
    awsCredentials: 'CodeFuller @ AWS'
    stackName: 'eks-cluster-role'
    templateSource: 'file'
    templateFile: 'eks-cluster-role.yaml'
