pool:
  name: Azure Pipelines
steps:
- task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
  displayName: 'Create Stack: VPC for EKS Cluster'
  inputs:
    awsCredentials: 'CodeFuller @ AWS'
    stackName: 'vpc-for-eks'
    templateFile: 'vpc-for-eks.yaml'
