pool:
  name: Azure Pipelines
  # Windows is required for AWSPowerShellModuleScript@1 task
  vmImage: vs2017-win2016

trigger: none

variables:
  AWS.Region: us-east-1
  AWS.Credentials: CodeFuller @ AWS

steps:
- task: AWSPowerShellModuleScript@1
  displayName: 'Load EKS Cluster Name'
  inputs:
    awsCredentials: 'CodeFuller @ AWS'
    scriptType: inline
    inlineScript: |
     Write-Host "Loading cluster name ..."
     $ClusterName = aws cloudformation describe-stacks --stack-name eks-cluster --query "Stacks[0].Outputs[?OutputKey=='ClusterName'].OutputValue" --output text
     Write-Host "Loaded cluster name '$ClsuterName'"
     Write-Host "##vso[task.setvariable variable=ClusterName;isSecret=false]$ClusterName"

- task: PowerShell@2
  displayName: 'Delete EKS Service Connection'
  inputs:
    targetType: filePath
    filePath: ./pipelines/delete-eks-service-connection.ps1
    arguments: '-PersonalToken $(ApiPersonalToken) -OrganizationUrl $(System.CollectionUri) -ProjectId $(System.TeamProjectId) -ProjectName $(System.TeamProject) -ClusterName $(ClusterName)'
    failOnStderr: true

- task: CloudFormationDeleteStack@1
  displayName: 'Delete Stack: IAM Role for EKS ALB Controller'
  inputs:
    awsCredentials: $(AWS.Credentials)
    stackName: eks-alb-controller-role

- task: CloudFormationDeleteStack@1
  displayName: 'Delete Stack: EKS Nodes Group'
  inputs:
    awsCredentials: $(AWS.Credentials)
    stackName: eks-nodes-group

- task: CloudFormationDeleteStack@1
  displayName: 'Delete Stack: EKS Cluster'
  inputs:
    awsCredentials: $(AWS.Credentials)
    stackName: eks-cluster

- task: CloudFormationDeleteStack@1
  displayName: 'Delete Stack: EKS VPC'
  inputs:
    awsCredentials: $(AWS.Credentials)
    stackName: eks-vpc
