parameters:
- name: envName
  type: string

- name: envDisplayName
  type: string

- name: domainName
  type: string

stages:
- stage: CreateResourcesFor${{ parameters.envDisplayName }}
  displayName: Create Resources for ${{ parameters.envDisplayName }} Environment
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  jobs:
  - deployment: CreateResourcesJob
    displayName: Create Resources for ${{ parameters.envDisplayName }} Environment
    environment: ${{ parameters.envName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: Kubernetes@1
            displayName: Create Namespace
            inputs:
              kubernetesServiceEndpoint: $(KubernetesConnectionName)
              command: apply
              arguments: -f namespace-${{ parameters.envName }}.yaml
              outputFormat: none

          - task: HelmDeploy@0
            displayName: Create Ingress
            inputs:
              connectionType: Kubernetes Service Connection
              kubernetesServiceConnection: $(KubernetesConnectionName)
              namespace: musicfeed-${{ parameters.envName }}
              command: upgrade
              chartType: FilePath
              chartPath: ./musicfeed-ingress
              releaseName: musicfeed-ingress
              overrideValues: |
                domainName=${{ parameters.domainName }}
                certificateArn=$(AWS.CertificateArn)
