parameters:
- name: envName
  type: string
- name: envDisplayName
  type: string

stages:
- stage: DeleteResourcesFor${{ parameters.envDisplayName }}
  displayName: Delete Resources for ${{ parameters.envDisplayName }} Environment
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  jobs:
  - deployment: DeleteResourcesJob
    displayName: Delete Resources for ${{ parameters.envDisplayName }} Environment
    environment: ${{ parameters.envName }}
    variables:
      - group: MusicFeedVariables.${{ parameters.EnvName }}
    strategy:
      runOnce:
        deploy:
          - checkout: self

          # We delete namespace so that ALB controller could delete load balancers provisioned for Ingress resources.
          - task: Kubernetes@1
            displayName: Delete Namespace
            inputs:
              kubernetesServiceEndpoint: $(KubernetesConnectionName)
              command: delete
              arguments: -f namespace-${{ parameters.envName }}.yaml
