parameters:
- name: envName
  type: string

- name: envDisplayName
  type: string

stages:
- stage: DeleteResourcesFor${{ parameters.envDisplayName }}
  displayName: Delete Resources for ${{ parameters.envDisplayName }} Environment
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
  jobs:
  - deployment: DeleteResourcesJob
    displayName: Delete Resources for ${{ parameters.envDisplayName }} Environment
    environment: ${{ parameters.envName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: HelmDeploy@0
            displayName: Uninstall Ingress Chart
            inputs:
              connectionType: Kubernetes Service Connection
              kubernetesServiceConnection: $(KubernetesConnectionName)
              namespace: musicfeed-${{ parameters.envName }}
              command: uninstall
              arguments: musicfeed-ingress
