# Source: https://stackoverflow.com/questions/56914173/

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipelines-robot
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: pipelines-robot-secret
  annotations:
    kubernetes.io/service-account.name: pipelines-robot
type: kubernetes.io/service-account-token
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-robot-rolebinding
subjects:
- kind: ServiceAccount
  name: pipelines-robot
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
