apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: musicfeed
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domainName }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
spec:
  rules:
    - http:
        paths:
          - path: /diagnostics/*
            backend:
              serviceName: diagnostics-service
              servicePort: 80

          - path: /api/*
            backend:
              serviceName: api-service
              servicePort: 80
